disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Isaac Miró portfolio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Isaac Miró (Proteus23). My personal portfolio as a Computer Science student at FIB UPC."

["params.author"]
name = "Isaac Miró"
bio = "Estudiant d'Enginyeria Informàtica"
headline = "Computer Science Engineering Student"
image = "isaac_face.jpg"
imageQuality = ""
email = "isaac.miro@estudiantat.upc.edu"

  [["params.author".links]]
  github = "https://github.com/Proteus233"

  [["params.author".links]]
  linkedin = "https://www.linkedin.com/in/isaac-miro-garcia/"
