disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Proteus23 portfolio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "My personal portfolio as a Computer Science student"

["params.author"]
name = "Isaac Miró"
bio = "Estudiant d'Enginyeria Informàtica"
headline = "Computer Science Engineering Student"

  [["params.author".links]]
  github = "https://github.com/Proteus233/hugo_portfolio"

  [["params.author".links]]
  linkedin = "https://www.linkedin.com/public-profile/settings/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_self_edit_contact_info%3BAaqS3PTfREa%2ByznbKx6GZg%3D%3D"
