[[main]]
none = "none"

[[main]]
  name    = "About me"
  pageRef = "about"
  weight  = 10
 

[[main]]
name = "My homelab"
pageRef = "homelab"
identifier = "B471XTEULd"
weight = 9_999

[[footer]]
none = "none"
